In [77]:
import numpy as np
import pandas as pd
import ast

In [91]:
workua = pd.read_csv("../data_2/csvs/workua_set_24_03.csv")
rabotaua = pd.read_csv("../data_2/csvs/robotaua_set_24_03.csv")
g = pd.read_csv("../data_2/csvs/final_set_24_03.csv", parse_dates=["published_datetime"])

In [92]:
g.info()

<class 'pandas.DataFrame'>
RangeIndex: 1127 entries, 0 to 1126
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1127 non-null   str
 1   company             1123 non-null   str
 2   location            1127 non-null   str
 3   salary_min          238 non-null    float64
 4   salary_max          238 non-null    float64
 5   average_salary      1127 non-null   float64
 6   skills              1127 non-null   str
 7   employment_type     1124 non-null   str
 8   experience_years    520 non-null    float64
 9   education           520 non-null    str
 10  published_datetime  1127 non-null   datetime64[us]
 11  recruiter_name      664 non-null    str
 12  recruiter_phone     520 non-null    str
 13  link                1127 non-null   str
 14  search_query        1127 non-null   str
 15  source              1127 non-null   str
dtypes: datetime64[us](1), float64(4), str(11)
memory usage: 141.0 KB

In [65]:
res = pd.read_csv("../data_2/csvs/final_concated_24_03.csv", parse_dates=["published_datetime"])

In [68]:
res['recruiter_phone']

0                      NaN
1                      NaN
2       t.me/+380676435158
3                      NaN
4       t.me/+380937725613
               ...
1568                   NaN
1569    t.me/+380939730736
1570                   NaN
1571                   NaN
1572                   NaN
Name: recruiter_phone, Length: 1573, dtype: str

In [11]:
res.info()

<class 'pandas.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1573 non-null   str
 1   company             1569 non-null   str
 2   location            1573 non-null   str
 3   salary_min          917 non-null    float64
 4   salary_max          917 non-null    float64
 5   average_salary      917 non-null    float64
 6   skills              1573 non-null   str
 7   employment_type     1570 non-null   str
 8   experience_years    959 non-null    float64
 9   education           959 non-null    str
 10  published_datetime  1463 non-null   str
 11  recruiter_name      877 non-null    str
 12  recruiter_phone     597 non-null    str
 13  link                1573 non-null   str
 14  search_query        1573 non-null   str
 15  source              614 non-null    str
dtypes: float64(4), str(12)
memory usage: 196.8 KB

In [12]:
res['published_datetime']

0       2026-03-24 13:39:25
1       2026-03-24 13:39:27
2       2026-03-24 13:39:28
3       2026-03-24 13:39:30
4       2026-03-24 13:39:31
               ...
1568                    NaN
1569                    NaN
1570    2026-03-20 14:45:15
1571    2026-03-10 14:45:15
1572    2026-03-10 14:45:15
Name: published_datetime, Length: 1573, dtype: str

In [14]:
res["recruiter_phone"].notna().sum()

np.int64(597)

In [16]:
res.loc[res["source"].isna(), "source"] = 'workua'
res.isna().sum()

title                   0
company                 4
location                0
salary_min            656
salary_max            656
average_salary        656
skills                  0
employment_type         3
experience_years      614
education             614
published_datetime    110
recruiter_name        696
recruiter_phone       976
link                    0
search_query            0
source                  0
dtype: int64

In [71]:
res[res['average_salary'] == 175000]

,title,company,location,salary_min,salary_max,average_salary,skills,employment_type,experience_years,education,published_datetime,recruiter_name,recruiter_phone,link,search_query,source
613,Head of marketing,"Доця Т. В., ФОП",Remote,150000.0,200000.0,175000.0,"['SEO', 'Google Ads', 'Google Shopping', 'Кому...",Повна зайнятість,5.0,Вища освіта,2026-03-23 16:22:23,NaN,NaN,https://www.work.ua/jobs/7844742/,marketing analyst,workua

In [69]:
res[["salary_min", "salary_max", "average_salary"]].describe()

          salary_min     salary_max  average_salary
count     917.000000     917.000000     1573.000000
mean    17358.258451   25256.830971    22370.609007
std     23105.526867   35691.960002    22643.946741
min         0.000000       0.000000        0.000000
25%         0.000000       0.000000        0.000000
50%         0.000000       0.000000    20235.858871
75%     33000.000000   45000.000000    32695.032051
max    150000.000000  200000.000000   175000.000000

In [18]:
res['published_datetime'] = pd.to_datetime(res['published_datetime'])
res.loc[res['published_datetime'].isna(), "published_datetime"] = pd.Timestamp.now()

res.isna().sum()

title                   0
company                 4
location                0
salary_min            656
salary_max            656
average_salary        656
skills                  0
employment_type         3
experience_years      614
education             614
published_datetime      0
recruiter_name        696
recruiter_phone       976
link                    0
search_query            0
source                  0
dtype: int64

In [73]:
res["search_query"] = res["search_query"].str.lower()
res["salary_min"] = res["salary_min"].replace(0, np.nan)
res["salary_max"] = res["salary_max"].replace(0, np.nan)
res.groupby('search_query')['average_salary'].mean()

search_query
bi analyst           64444.444444
business analyst     11365.518966
data analyst         25828.645833
data scientist           0.000000
financial analyst    20235.858871
marketing analyst    32695.032051
product analyst      17500.000000
system analyst       50694.444444
Name: average_salary, dtype: float64

In [21]:

averages = res.groupby('search_query')['average_salary'].mean()

search_query
bi analyst           54375.000000
business analyst     11365.518966
data analyst         25828.645833
data scientist           0.000000
financial analyst    20235.858871
marketing analyst    32695.032051
product analyst      17500.000000
system analyst       50694.444444
Name: average_salary, dtype: float64

In [26]:
type(averages)

pandas.Series

In [24]:
res.loc[res["average_salary"].isna(), "average_salary"] =

In [25]:
averages = res.groupby('search_query')['average_salary'].mean()
averages

search_query
bi analyst           54375.000000
business analyst     11365.518966
data analyst         25828.645833
data scientist           0.000000
financial analyst    20235.858871
marketing analyst    32695.032051
product analyst      17500.000000
system analyst       50694.444444
Name: average_salary, dtype: float64

In [35]:
res["average_salary"] = res["average_salary"].fillna(
    res["search_query"].map(averages))

In [36]:
res.isna().sum()

title                   0
company                 4
location                0
salary_min            656
salary_max            656
average_salary          0
skills                  0
employment_type         3
experience_years      614
education             614
published_datetime      0
recruiter_name        696
recruiter_phone       976
link                    0
search_query            0
source                  0
dtype: int64

In [62]:
def pick_phone(phone_list):
    phones = [p for p in phone_list if pd.notna(p)]
    return phones[0] if phones else None

company_phone_map = (res.groupby('company')['recruiter_phone'].apply(lambda x: pick_phone(x.unique())))
res['recruiter_phone'] = res['recruiter_phone'].fillna(res['company'].map(company_phone_map))

title                   0
company                 4
location                0
salary_min            656
salary_max            656
average_salary          0
skills                  0
employment_type         3
experience_years      614
education             614
published_datetime      0
recruiter_name        696
recruiter_phone       826
link                    0
search_query            0
source                  0
dtype: int64

In [37]:
res['company'].unique()

<StringArray>
[                                                         'Біосфера, корпорація',
                                                                      'Moneyveo',
                                                                'Universal Bank',
                                               'Касьянова К.С., ФОП (AutoHaven)',
                                                               'Pro recruitment',
                                                                  'Ajax Systems',
                                                'Кондитерська Корпорація ROSHEN',
                                                                'Паркінг+, ТзОВ',
                                                          'Брокард-Україна, ТОВ',
                                              'Є гроші, фінансова компанія, ТОВ',
 ...
                                                                 'ЗТДніпро, ТОВ',
                                                   'СІСТЕМ ІНЖИНІРИНГ ГРУП, ТОВ',
                                                                      'SevenPro',
                                                              'БЕЙСПАК, ТОВ, ТД',
 'Батальйон оперативного призначення АТЕЙ 28 полку Національної гвардії України',
                                                              'ФЕОФАНІЯ лікарня',
                                                                     'ABM Cloud',
                                                        'Банк Кредит Дніпро, АТ',
                                                      'Catholic Relief Services',
                                                                       'HRAVITY']
Length: 944, dtype: str

In [76]:
temp = res.duplicated(subset="link")
temp.any()

np.False_

In [79]:



def parse_skills(x):
    # если строка → пробуем преобразовать
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)
            return parsed if isinstance(parsed, list) else []
        except:
            return []

    # если уже список
    if isinstance(x, list):
        return x

    # всё остальное → пусто
    return []

In [80]:
# 1. преобразуем в списки
res["skills"] = res["skills"].apply(parse_skills)

# 2. нормализуем (lower + trim)
res["skills"] = res["skills"].apply(
    lambda x: [s.strip().lower() for s in x if isinstance(s, str)]
)

In [ ]:

# 3. удаляем пустые
df = res[res["skills"].apply(len) > 0]

In [82]:
res['skills']

0       [користувач 1с, знання законодавства україни, ...
1       [користувач erp-системи, користувач bas, здатн...
2       [ms excel, фінансовий аналіз, фінансове планув...
3       [ms excel, користувач 1с, ведення бухгалтерськ...
4       [ms excel, користувач 1с, організаторські здіб...
                              ...
1568    [sql, python, etl, api, azure, hadoop, spark, ...
1569    [sql, python, scikit-learn, tensorflow, machin...
1570                 [git, machine learning, sql, python]
1571                               [power bi, excel, git]
1572    [power bi, sql, python, nlp, machine learning,...
Name: skills, Length: 1573, dtype: object

In [83]:

SKILL_MAP = {
    "python": ["python"],
    "sql": ["sql", "postgres", "mysql", "pl/sql"],
    "excel": ["excel", "google sheets", "sheets"],
    "power bi": ["power bi", "powerbi"],
    "tableau": ["tableau"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "statistics": ["statistics"],
    "machine learning": ["machine learning", "ml"],
    "etl": ["etl"],
    "api": ["api"],
    "git": ["git", "github", "gitlab"],
    "aws": ["aws"],
    "gcp": ["gcp"],
    "azure": ["azure"]
}

def process_skills(x):
    # 1. строка → список
    if isinstance(x, str):
        try:
            skills_list = ast.literal_eval(x)
        except:
            return []
    elif isinstance(x, list):
        skills_list = x
    else:
        return []

    # 2. нормализация + фильтрация
    result = set()

    for skill in skills_list:
        if not isinstance(skill, str):
            continue

        s = skill.lower().strip()

        for normalized, variants in SKILL_MAP.items():
            if any(v in s for v in variants):
                result.add(normalized)
                break

    return list(result)

# применяем
res["skills"] = res["skills"].apply(process_skills)

# удаляем пустые
res = res[res["skills"].apply(len) > 0]

In [88]:
res['skills']

2                                                 [excel]
3                                                 [excel]
4                                                 [excel]
6                                       [power bi, excel]
7                                                 [excel]
                              ...
1568                  [api, etl, azure, python, sql, aws]
1569                 [sql, machine learning, git, python]
1570                 [sql, machine learning, git, python]
1571                               [power bi, git, excel]
1572    [power bi, python, sql, machine learning, tabl...
Name: skills, Length: 1127, dtype: object

In [ ]:
g = pd.read_csv("")